Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NewsManagementDotNetCoreApp.Data;
using NewsManagementDotNetCoreApp.Models;
using NewsManagementDotNetCoreApp.Models.PostViewModels;
using NewsManagementDotNetCoreApp.StaticFolder;

namespace NewsManagementDotNetCoreApp.Controllers
{
    [Authorize(Roles = SD.AdminEndUser)]
    public class PostsController : Controller
    {        
        private readonly ApplicationDbContext _db;
        private readonly IHostingEnvironment _hostingEnviroment;

        [BindProperty]
        public PostViewModel PostViewModelVM { get; set; }

        public PostsController(ApplicationDbContext db, IHostingEnvironment hostingEnvironment)
        {
            _db = db;

            _hostingEnviroment = hostingEnvironment;

            PostViewModelVM = new PostViewModel()
            {
                Category = _db.Categories.ToList(),
                PostPlace = _db.PostPlaces.ToList(),
                Post = new Post()
            };
        }

        public async Task<IActionResult> Index()
        {
            var posts = _db.Posts.Include(m => m.Category).Include(m => m.SubCategory).Include(m => m.PostPlace);
            return View(await posts.ToListAsync());
        }






        // GET: Post Create
        public IActionResult Create() => View(PostViewModelVM);

        // POST : Post Create
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePOST()
        {
            PostViewModelVM.Post.SubCategoryId = Convert.ToInt32(Request.Form["SubCategoryId"].ToString());
            PostViewModelVM.Post.Video = "default_video";

            if (!ModelState.IsValid)
            {
                return View(PostViewModelVM);
            }

            _db.Posts.Add(PostViewModelVM.Post);
            await _db.SaveChangesAsync();

            //Image Being Saved
            string webRootPath = _hostingEnviroment.WebRootPath;
            var files = HttpContext.Request.Form.Files;

            var postFromDb = _db.Posts.Find(PostViewModelVM.Post.ID);

            if (files[0] != null && files[0].Length > 0)
            {
                //when user uploads an image
                var uploads = Path.Combine(webRootPath, "images");
                var extension = files[0].FileName.Substring(files[0].FileName.LastIndexOf("."), files[0].FileName.Length - files[0].FileName.LastIndexOf("."));

                using (var filestream = new FileStream(Path.Combine(uploads, PostViewModelVM.Post.ID + extension), FileMode.Create))
                {
                    files[0].CopyTo(filestream);
                }
                postFromDb.Image = @"\images\" + PostViewModelVM.Post.ID + extension;
            }
            else
            {
                //when user does not upload image
                var uploads = Path.Combine(webRootPath, @"images\" + SD.DefaultNewsImage);
                System.IO.File.Copy(uploads, webRootPath + @"\images\" + PostViewModelVM.Post.ID + ".png");
                postFromDb.Image = @"\images\" + PostViewModelVM.Post.ID + ".png";
            }

            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));

        }

        // Get JSON Result For SubCategories
        public JsonResult GetSubCategory(int CategoryId)
        {
            List<SubCategory> subCategoryList = new List<SubCategory>();

            subCategoryList = (from subCategory in _db.SubCategories
                               where subCategory.CategoryId == CategoryId
                               select subCategory).ToList();

            return Json(new SelectList(subCategoryList, "ID", "Name"));
        }

        //GET : Edit Posts
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            PostViewModelVM.Post = await _db.Posts.Include(m=>m.Category).Include(m => m.SubCategory).Include(m=>m.PostPlace).SingleOrDefaultAsync(m => m.ID == id);
            PostViewModelVM.SubCategory = _db.SubCategories.Where(s => s.CategoryId == PostViewModelVM.Post.CategoryId).ToList();

            if (PostViewModelVM.Post == null)
            {
                return NotFound();
            }

            return View(PostViewModelVM);
        }



        //POST : Edit Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id)
        {
            PostViewModelVM.Post.SubCategoryId = Convert.ToInt32(Request.Form["SubCategoryId"].ToString());

            if (id != PostViewModelVM.Post.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string webRootPath = _hostingEnviroment.WebRootPath;
                    var files = HttpContext.Request.Form.Files;
                    var postFromDb = _db.Posts.Where(m => m.ID == PostViewModelVM.Post.ID).FirstOrDefault();

                    if (files[0].Length > 0 && files[0] != null)
                    {
                        //if user uploads a new image
                        var uploads = Path.Combine(webRootPath, "images");

                        var extension_New = files[0].FileName.Substring(files[0].FileName.LastIndexOf("."), files[0].FileName.Length - files[0].FileName.LastIndexOf("."));

                        var extension_Old = postFromDb.Image.Substring(postFromDb.Image.LastIndexOf("."), postFromDb.Image.Length - postFromDb.Image.LastIndexOf("."));

                        if (System.IO.File.Exists(Path.Combine(uploads, PostViewModelVM.Post.ID + extension_Old)))
                        {
                            System.IO.File.Delete(Path.Combine(uploads, PostViewModelVM.Post.ID + extension_Old));
                        }
                        using (var filestream = new FileStream(Path.Combine(uploads, PostViewModelVM.Post.ID + extension_New), FileMode.Create))
                        {
                            files[0].CopyTo(filestream);
                        }
                        PostViewModelVM.Post.Image = @"\images\" + PostViewModelVM.Post.ID + extension_New;
                    }

                    if (PostViewModelVM.Post.Image != null)
                    {
                        postFromDb.Image = PostViewModelVM.Post.Image;
                    }
                    postFromDb.Name = PostViewModelVM.Post.Name;
                    postFromDb.Desc = PostViewModelVM.Post.Desc;
                    postFromDb.PostPlaceId = PostViewModelVM.Post.PostPlaceId;
                    postFromDb.CategoryId = PostViewModelVM.Post.CategoryId;
                    postFromDb.SubCategoryId = PostViewModelVM.Post.SubCategoryId;
                    await _db.SaveChangesAsync();
                }
                catch (Exception ex)
                {

                }
                return RedirectToAction(nameof(Index));
            }
            PostViewModelVM.SubCategory = _db.SubCategories.Where(s => s.CategoryId == PostViewModelVM.Post.CategoryId).ToList();
            return View(PostViewModelVM);

        }

        //GET : Details Posts
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            PostViewModelVM.Post = await _db.Posts.Include(m => m.Category).Include(m => m.SubCategory).Include(m=>m.PostPlace).SingleOrDefaultAsync(m => m.ID == id);

            if (PostViewModelVM.Post == null)
            {
                return NotFound();
            }

            return View(PostViewModelVM);
        }


        //GET : Delete Post
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            PostViewModelVM.Post = await _db.Posts.Include(m => m.Category).Include(m => m.SubCategory).Include(m=>m.PostPlace).SingleOrDefaultAsync(m => m.ID == id);

            if (PostViewModelVM.Post == null)
            {
                return NotFound();
            }

            return View(PostViewModelVM);
        }

        //POST Delete MenuItem
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            string webRootPath = _hostingEnviroment.WebRootPath;
            Post postItem = await _db.Posts.FindAsync(id);

            if (postItem != null)
            {
                var uploads = Path.Combine(webRootPath, "images");
                var extension = postItem.Image.Substring(postItem.Image.LastIndexOf("."), postItem.Image.Length - postItem.Image.LastIndexOf("."));

                var imagePath = Path.Combine(uploads, postItem.ID + extension);
                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }
                _db.Posts.Remove(postItem);
                await _db.SaveChangesAsync();

            }

            return RedirectToAction(nameof(Index));
        }


    }
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NewsManagementDotNetCoreApp.Data;
using NewsManagementDotNetCoreApp.Models;
using NewsManagementDotNetCoreApp.StaticFolder;

namespace NewsManagementDotNetCoreApp.Controllers
{
        [Authorize(Roles = SD.AdminEndUser)]
        public class UsersController : Controller
        {
            private readonly ApplicationDbContext _context;

            public UsersController(ApplicationDbContext context)
            {
                _context = context;
            }

            // GET: Users
            public async Task<IActionResult> Index()
            {
                var claimsIdentity = (ClaimsIdentity)this.User.Identity;
                var claim = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);

                return View(await _context.ApplicationUser.Where(u => u.Id != claim.Value).ToListAsync());
            }



            // GET: Users/Edit/5
            public async Task<IActionResult> Edit(string id)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);

                if (applicationUser == null)
                {
                    return NotFound();
                }
                return View(applicationUser);
            }

            // POST: Users/Edit/5
            // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
            // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Edit(string id, ApplicationUser model)
            {
                if (id != model.Id)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    var userFromDb = await _context.Users.Where(u => u.Id == id).FirstOrDefaultAsync();

                    userFromDb.FirstName = model.FirstName;
                    userFromDb.LastName = model.LastName;
                    userFromDb.PhoneNumber = model.PhoneNumber;
                    userFromDb.LockoutEnd = model.LockoutEnd;
                    userFromDb.LockoutEnabled = model.LockoutEnabled;
                    userFromDb.AccessFailedCount = model.AccessFailedCount;
                    userFromDb.LockoutReason = model.LockoutReason;
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                return View(model);
            }

            public async Task<IActionResult> Lock(string id)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var applicationUser = await _context.ApplicationUser
                    .SingleOrDefaultAsync(m => m.Id == id);
                if (applicationUser == null)
                {
                    return NotFound();
                }

                return View(applicationUser);
            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Lock(string id, ApplicationUser model)
            {
                var userFromDb = await _context.Users.Where(u => u.Id == id).FirstOrDefaultAsync();

                userFromDb.FirstName = model.FirstName;
                userFromDb.LastName = model.LastName;
                userFromDb.PhoneNumber = model.PhoneNumber;
                userFromDb.LockoutEnd = DateTime.Now.AddYears(100);
                userFromDb.LockoutEnabled = model.LockoutEnabled;
                userFromDb.AccessFailedCount = model.AccessFailedCount;
                userFromDb.LockoutReason = model.LockoutReason;
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            private bool ApplicationUserExists(string id)
            {
                return _context.ApplicationUser.Any(e => e.Id == id);
            }
        }
}

Views/Shared/_CategoryFirstPost.cshtml
@model IEnumerable<Post>

@foreach (var item in Model)
{
    <div class="col-md-12">
        <div class="feature_news_item category_item">
            <div class="item">
                <div class="item_wrapper">
                    <div class="item_img">
                        <img style="width:100%;" class="img-responsive" src="@item.Image" alt="@item.Name">
                    </div><!--item_img-->
                    <div class="item_title_date">
                        <div class="news_item_title">
                            <h1><a href="~/home/readpost/@item.ID">@item.Name</a></h1>
                        </div><!--news_item_title-->
                        <div class="item_meta"><a href="~/home/readpost/@item.ID">@item.Date,</a> Sub Category:<a href="#">@item.SubCategory.Name</a></div>
                    </div><!--item_title_date-->
                </div><!--item_wrapper-->
                <!--item_content-->
            </div><!--item-->
        </div><!--feature_news_item-->
    </div><!--col-md-6-->
}

Views/Shared/_CategoryPartial.cshtml
@model IEnumerable<Post>

@{

    var SelectLeftSideNews = (from Item in Model
                               orderby Item.ID descending
                               select Item).Take(1);

    var SelectRightSideNews = (from Item in Model
                               orderby Item.ID descending
                               select Item).Skip(1).Take(4);

}


    <div class="row">
        @foreach (var item in SelectLeftSideNews)
        {
            <div class="col-md-7">
                <div class="item active feature_news_item">
                    <div class="item_wrapper">
                        <div class="item_img">
                            <img class="img-responsive" src="@item.Image" alt="@item.Name">
                        </div><!--item_img-->
                        <div class="item_title_date">
                            <div class="news_item_title">
                                <h2><a href="~/home/readpost/@item.ID">@item.Name</a></h2>
                            </div><!--news_item_title-->
                            <div class="item_meta">@item.Date Sub Category:@item.SubCategory.Name</div>
                        </div><!--item_title_date-->
                    </div><!--item_wrapper-->
                </div><!--feature_news_item-->
            </div><!--col-md-7-->
        }


        <div class="col-md-5">
            <div class="media_wrapper">


                @foreach (var item in SelectRightSideNews)
                {
                    <div class="media">
                        <div class="media-left">
                            <a href="~/home/readpost/@item.ID"><img class="media-object" style="width:80px;height:80px;" src="@item.Image" alt="@item.Name"></a>
                        </div><!--media-left-->
                        <div class="media-body">
                            <h3 class="media-heading">
                                <a href="~/home/readpost/@item.ID">
                                    @item.Name
                                </a>
                            </h3>
                        </div><!--media-body-->
                    </div><!--media-->
                }


            </div><!--media_wrapper-->
        </div><!--col-md-5-->
    </div><!--row-->

Views/Shared/_CategoryRelatedNews.cshtml
@model IEnumerable<Post>

@foreach (var item in Model)
{
    <div class="col-md-6">
        <div class="feature_news_item">
            <div class="item">
                <div class="item_wrapper">
                    <div class="item_img">
                        <img style="width:408px;height:306px;" class="img-responsive" src="@item.Image" alt="@item.Name">
                    </div> <!--item_img-->
                    <div class="item_title_date">
                        <div class="news_item_title">
                            <h2><a href="~/home/readpost/@item.ID">@item.Name</a></h2>
                        </div>
                        <div class="item_meta">@item.Date Sub Category: @item.SubCategory.Name </div>
                    </div><!--item_title_date-->
                </div> <!--item_wrapper-->
            </div><!--item-->
        </div><!--feature_news_item-->
    </div><!--col-md-6-->
}

Views/Shared/_FeaturedVideos.cshtml
@model IEnumerable<Post>


<div class="feature_video_title"><h2>Featured Videos</h2></div>
<div id="feature_video_slider" class="owl-carousel">

    @foreach (var item in Model)
    {
        <div class="item">
            <div class="video_thumb"><img style="width:340px;height:188px" src="@item.Image" alt="@item.Name"></div>
            <div class="video_info">
                <div class="video_item_title"><h3><a href="~/home/readpost/@item.ID">@item.Name</a></h3></div><!--video_item_title-->
                <div class="item_meta">@item.Date</div><!--item_meta-->
            </div><!--video_info-->
        </div>
    }

</div><!--feature_video_slider-->

Views/Shared/_LatestSide.cshtml
@model IEnumerable<Post>

@foreach (var item in Model)
{
    <div class="media">
        <div class="media-left">
            <a href="~/home/readpost/@item.ID"><img style="width:80px;height:80px;" class="media-object" src="@item.Image" alt="@item.Name"></a>
        </div><!--media-left-->
        <div class="media-body">
            <h4 class="media-heading"><a href="~/home/readpost/@item.ID">@item.Name</a></h4>
        </div><!--media-body-->
    </div><!--media-->
}

Views/Shared/_Layout.cshtml
@using NewsManagementDotNetCoreApp.StaticFolder
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NewsManagementDotNetCoreApp</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">NewsManagementDotNetCoreApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>

                    @if (User.IsInRole(SD.AdminEndUser))
                    {
                        <li><a asp-area="" asp-controller="Posts" asp-action="Index">Posts</a></li>
                        <li><a asp-area="" asp-controller="PostPlaces" asp-action="Index">Post Places</a></li>
                        <li><a asp-area="" asp-controller="Categories" asp-action="Index">Categories</a></li>
                        <li><a asp-area="" asp-controller="SubCategories" asp-action="Index">Sub Categories</a></li>
                        <li><a asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                    }

                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - NewsManagementDotNetCoreApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_LoginPartialButton.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<p>
    <a asp-action="Create">Create New</a>
</p>

Views/Shared/_MoreNewsPartial.cshtml
@model IEnumerable<Post>

@foreach (var item in Model)
{
    <div class="col-md-4">
        <div class="feature_news_item">
            <div class="item">
                <div class="item_wrapper">
                    <div class="item_img">
                        <img class="img-responsive" style="width:263px; height:177px" src="@item.Image" alt="@item.Name">
                    </div><!--item_img-->
                    <div class="item_title_date">
                        <div class="news_item_title">
                            <h3><a href="~/home/readpost/@item.ID">@item.Name</a></h3>
                        </div><!--news_item_title-->
                        <div class="item_meta">@item.Date Sub Category:@item.SubCategory.Name</div>
                    </div><!--item_title_date-->
                </div><!--item_wrapper-->

            </div><!--item-->
        </div><!--feature_news_item-->
    </div><!--col-xs-4-->
}

Views/Shared/_MostCommented.cshtml
@model IEnumerable<Post>

@foreach (var item in Model)
{
    <div class="media">
        <div class="media-left">
            <a href="~/home/readpost/@item.ID"><img style="width:80px;height:80px;" class="media-object" src="@item.Image" alt="@item.Name"></a>
        </div><!--media-left-->
        <div class="media-body">
            <h3 class="media-heading"><a href="~/home/readpost/@item.ID">@item.Name</a></h3>
        </div><!--media-body-->
    </div><!--media-->
}

Views/Shared/_ReadPostRelatedNews.cshtml
@model IEnumerable<Post>

<div class="single_related_news">
    <div class="single_media_title"><h2>Related News</h2></div>
    <div class="media_wrapper">

        @foreach (var item in Model)
        {
            <div class="media">
                <div class="media-left">
                    <a href="~/home/readpost/@item.ID"><img style="width:80px;height:80px;" class="media-object" src="@item.Image" alt="@item.Name"></a>
                </div><!--media-left-->
                <div class="media-body">
                    <h4 class="media-heading">
                        <a href="~/home/readpost/@item.ID">
                            @item.Name
                        </a>
                    </h4>
                    <div class="media_meta">@item.Date, Sub Category: @item.Category.Name</div>
                </div><!--media-body-->
            </div><!--media-->
        }

    </div><!--media_wrapper-->
</div><!--single_related_news-->

Views/Shared/_SliderAsidePartial.cshtml
@model IEnumerable<Post>

<div class="col-md-6">
    <div class="feature_news_static">
        <div class="row">

            @foreach (var item in Model)
            {
                <div class="col-md-6">
                    <div class="feature_news_item">
                        <div class="item active">
                            <div class="item_wrapper">
                                <div class="item_img">
                                    <img style="height:415px" class="img-responsive" src="@item.Image" alt="@item.Name">
                                </div> <!--item_img-->
                                <div class="item_title_date">
                                    <div class="news_item_title">
                                        <h2><a href="~/home/readpost/@item.ID">@item.Name</a></h2>
                                    </div>
                                    <div class="item_meta">@item.Date Sub Category: @item.SubCategory.Name</div>
                                </div><!--item_title_date-->
                            </div> <!--item_wrapper-->
                            
                        </div><!--item-->
                    </div><!--feature_news_item-->
                </div>
            }

        </div><!--row-->
    </div><!--feature_news_static-->
</div><!--col-md-6-->

Views/Shared/_SliderPartial.cshtml
@model IEnumerable<Post>

@{

    var SelectSliderFirstElement = (from Item in Model
                              orderby Item.ID descending
                              select Item).Take(1);

    var SelectSliderAnotherElements = (from Item in Model
                               orderby Item.ID descending
                               select Item).Skip(1).Take(4);

}


<div class="col-md-6">
    <div class="feature_news_carousel">
        <div id="featured-news-carousal" class="carousel slide" data-ride="carousel">
            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">

                @foreach (var item in SelectSliderFirstElement)
                {
                    <div class="item active feature_news_item">
                        <div class="item_wrapper">
                            <div class="item_img">
                                <img style="width:100%;" class="img-responsive" src="@item.Image" alt="@item.Name">
                            </div> <!--item_img-->
                            <div class="item_title_date">
                                <div class="news_item_title">
                                    <h2><a href="~/home/readpost/@item.ID">@item.Name</a></h2>
                                </div>
                                <div class="item_meta">@item.Date Sub Category:@item.SubCategory.Name</div>
                            </div> <!--item_title_date-->
                        </div>	<!--item_wrapper-->
                        
                    </div>
                }


                @foreach (var item in SelectSliderAnotherElements)
                {
                    <div class="item feature_news_item">
                        <div class="item_wrapper">
                            <div class="item_img">
                                <img class="img-responsive" src="@item.Image" alt="@item.Name">
                            </div> <!--item_img-->
                            <div class="item_title_date">
                                <div class="news_item_title">
                                    <h2><a href="~/home/readpost/@item.ID">@item.Name</a></h2>
                                </div>
                                <div class="item_meta">@item.Date Sub Category:@item.SubCategory.Name</div>
                            </div> <!--item_title_date-->
                        </div>	<!--item_wrapper-->
                       
                    </div>
                }


                <!-- Left and right controls -->
                <div class="control-wrapper">
                    <a class="left carousel-control" href="#featured-news-carousal" role="button" data-slide="prev">
                        <i class="fa fa-chevron-left" aria-hidden="true"></i>
                    </a>
                    <a class="right carousel-control" href="#featured-news-carousal" role="button" data-slide="next">
                        <i class="fa fa-chevron-right" aria-hidden="true"></i>
                    </a>
                </div>
            </div><!--carousel-inner-->
        </div><!--carousel-->
    </div><!--feature_news_carousel-->
</div><!--col-md-6-->

Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}